In [28]:
import requests
import os 
from dotenv import load_dotenv
import pandas as pd
from sqlalchemy import create_engine

load_dotenv()

url = ('https://newsapi.org/v2/everything?'
       'q=Apple&'
       'from=2026-05-15&'
       'sortBy=popularity&'
       'apiKey=' + os.getenv('NEWS_API_KEY'))

response = requests.get(url)

response.json()

{'status': 'ok',
 'totalResults': 37427,
 'articles': [{'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Louryn Strampe',
   'title': 'Memorial Day Tech Deals: Sony, Apple, Beats (2026)',
   'description': 'Lots of our most-recommended headphones, power banks, and other gadgets are on sale for Memorial Day.',
   'url': 'https://www.wired.com/story/memorial-day-tech-deals-2026-1/',
   'urlToImage': 'https://media.wired.com/photos/6a06188db84b146a9eec38c1/191:100/w_1280,c_limit/Memorial%20Day%20Deals%20Tech%20top%20art%20052026%20SOURCE%20Amazon.jpg',
   'publishedAt': '2026-05-22T18:52:47Z',
   'content': "When you think of Memorial Day sales, you probably think of mattresses and other home goods. And while those items are definitely discounted, now is also a good time to purchase tech. Personally, I'm… [+1064 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Luke Larsen',
   'title': 'MacOS 27 Golden Gate: Top New Features',
   'description': "Apple has announced the latest version of macOS. It's all about the reintroduction of Siri, which is now accessible from anywhere on the Mac desktop.",
   'url': 'https://www.wired.com/story/macos-27-golden-gate-top-features/',
   'urlToImage': 'https://media.wired.com/photos/6a2849c20d6aa02c6a8cdf9e/191:100/w_1280,c_limit/Apple-OS-27-updates-260608.jpg',
   'publishedAt': '2026-06-09T17:33:21Z',
   'content': 'One of the most interesting new features is Custom Extensions, which lets you create an extension for Safari in natural language. Lastly, the new version of Safari will work the Passwords app to auto… [+2328 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Julian Chokkattu',
   'title': 'Apple’s iPhone Camera App Is Getting an AI Upgrade in iOS 27',
   'description': 'Siri is now directly embedded into the camera app, and there are more artificial intelligence tools in the Photos app to alter your images.',
   'url': 'https://www.wired.com/story/apples-iphone-camera-app-is-getting-an-ai-upgrade-in-ios-27/',
   'urlToImage': 'https://media.wired.com/photos/6a270a0e623237895b48f975/191:100/w_1280,c_limit/apple-camera-app-gear-2233007119.jpg',
   'publishedAt': '2026-06-08T18:40:32Z',
   'content': 'Your iPhone camera app will look a little different this fall. On Monday at its annual Worldwide Developers Conference in Cupertino, California, Apple showed off new features in its next version of i… [+2335 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Boutayna Chokrane',
   'title': '2 Best Bluetooth Trackers of 2026, Plus Honorable Mentions',
   'description': 'Constantly losing your stuff? Here are the best Bluetooth trackers to help you keep everything in check—plus some guidance on staying safe while using them.',
   'url': 'https://www.wired.com/story/the-best-bluetooth-trackers/',
   'urlToImage': 'https://media.wired.com/photos/6a232b2b713a46b95a632884/191:100/w_1280,c_limit/The-Best-Bluetooth-Trackers.jpg',
   'publishedAt': '2026-06-06T10:38:00Z',
   'content': "I'd like to believe I'm organized. Reality suggests otherwise. I've left my smartphone in the refrigerator and spent hours searching for it. I've misplaced my AirPods and Oura Ring for days at a time… [+2518 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Luke Larsen',
   'title': 'I Never Liked a Laptop Sleeve Until I Tried the Bellroy Laptop Caddy',
   'description': "The Bellroy Laptop Caddy is actually so much more than a laptop sleeve. With all the extra space and pockets, it's the best laptop companion I've ever used.",
   'url': 'https://www.wired.com/story/finally-a-laptop-sleeve-for-me/',
   'urlToImage': 'https://media.wired.com/photos/6a0cabd72c7ee96598e09971/191:100/w_1280,c_limit/Bellroy%20Laptop%20Caddy%20SOURCE%20Bellroy%20(Bag%20Check).jpg',
   'publishedAt': '2026-05-26T09:32:00Z',
   'content': 'As we get out of the house, the gear-obsessed WIRED Reviews team is writing about our favorite bags and EDCs. Today, reviewer Luke Larsenraves about his love for his Bellroy Laptop Caddy. You can als… [+2204 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Paresh Dave, Lauren Goode, Zoë Schiffer',
   'title': 'Meta Employees Are Scrambling to Use Up Benefits Ahead of Layoffs',
   'description': 'On the eve of about 8,000 jobs being cut, employees are cashing in on headphone stipends and other perks while they still can.',
   'url': 'https://www.wired.com/story/meta-employees-scramble-benefits-layoffs-ai/',
   'urlToImage': 'https://media.wired.com/photos/6a0cb2b791b600abc11af14d/191:100/w_1280,c_limit/Meta-Employees-Scrambling-to-Use-Up-Benefits-Ahead-of-Layoffs-Business-2272777092.jpg',
   'publishedAt': '2026-05-19T19:00:46Z',
   'content': 'Ahead of Metas latest round of mass layoffs tomorrow, some employees are deserting offices, abandoning their work, and loading up on perks they might soon lose, several people at the company tell WIR… [+2885 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Cameras get an Apple Intelligence boost in Apple Home',
   'description': 'Apple Intelligence is coming to cameras connected to Apple Home. At WWDC, Apple announced that with iOS27, the Home app will use Apple Intelligence to analyze footage and generate descriptions summarizing what the camera saw. You can also search footage with …',
   'url': 'https://www.theverge.com/tech/946032/apple-home-ai-camera-descriptions-search-4k',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Screenshot-2026-06-08-at-1.58.57PM.png?quality=90&strip=all&crop=0%2C3.5746394385138%2C100%2C92.850721122972&w=1200',
   'publishedAt': '2026-06-08T18:50:04Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nSecurity cameras connected to the Home app can use AI to search footage, and HomeKit Secure Video will finally support 4K resolution.\r\nSecurity cameras connected… [+2622 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jay Peters',
   'title': 'Apple announces iOS 27',
   'description': 'Apple announced its next major iOS update, iOS 27, at WWDC 2026 on Monday. Apple is highlighting performance and design improvements as a major feature, and the update will be supported all the way back to the iPhone 11. A big change is an opacity slider for …',
   'url': 'https://www.theverge.com/tech/941202/apple-ios-27-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/STK071_APPLE_E.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T17:23:57Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nYour iPhone is getting new features.\r\nYour iPhone is getting new features.\r\nby\r\nJay PetersClose\r\nPosts from this author will be added to your daily email digest … [+2895 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Andrew Liszewski',
   'title': 'Apple announces iPadOS 27',
   'description': "Today at Apple's Worldwide Developers Conference, the company announced new features coming to the iPad with iPadOS 27 including optimizations such as apps launching up to 30 percent faster by intelligently preloading needed info, and more responsive switchin…",
   'url': 'https://www.theverge.com/tech/942546/apple-ipados-27-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/ipados1.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T17:51:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe iPads next big update is expected to arrive later this year.\r\nThe iPads next big update is expected to arrive later this year.\r\nby\r\nAndrew LiszewskiClose\r\nPo… [+3864 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Robert Hart',
   'title': 'Apple wants Europe to blink',
   'description': "It took a few years, but Apple finally made its AI look useful. Now millions of iPhone users in Europe are being told they won't be getting Siri AI anytime soon, if ever - and Apple wants them to blame the EU. Apple says its new AI-powered Siri will not launc…",
   'url': 'https://www.theverge.com/ai-artificial-intelligence/947051/apple-europe-dma-siri-ai',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK450_EU_G.jpg?quality=90&strip=all&crop=0%2C9.9676601489831%2C100%2C80.064679702034&w=1200',
   'publishedAt': '2026-06-09T17:13:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nApple wants Europe to blink\r\nApple blames DMA for delaying Siri AI in Europe. The EU says nothing is stopping Apple from launching it. \r\nby\r\nRobert HartClose\r\nPo… [+7489 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple is using AI to fix Safari’s extension problem',
   'description': "Apple is trying to solve one of Safari's biggest weaknesses with AI. Safari has long lacked the robust library of extensions that its rivals have, mainly due to the stringent development requirements from Apple. But now, Apple is inviting users to essentially…",
   'url': 'https://www.theverge.com/tech/946345/apple-safari-ai-update-extensions',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/describe-extension-safari.jpg?quality=90&strip=all&crop=0%2C10.742998834307%2C100%2C78.514002331385&w=1200',
   'publishedAt': '2026-06-08T22:14:17Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nSafari will invite users to vibe-code their own extensions.\r\nSafari will invite users to vibe-code their own extensions.\r\nby\r\nEmma RothClose\r\nPosts from this aut… [+4329 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple WWDC 2026: The 7 biggest announcements',
   'description': "Apple's keynote at this year's Worldwide Developers Conference was a big one. After months of delays, Apple reintroduced us to its AI-upgraded Siri, which will go beyond what the existing voice assistant can do by offering more personalized help. We also got …",
   'url': 'https://www.theverge.com/tech/945693/apple-wwdc-2026-biggest-announcements-ios-27',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Screenshot-2026-06-08-at-1.01.41PM.png?quality=90&strip=all&crop=0%2C2.7453349442878%2C100%2C94.509330111424&w=1200',
   'publishedAt': '2026-06-08T18:51:19Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe update-filled keynote showed an AI-upgraded Siri along with new features across Apples operating systems.\r\nby\r\nEmma RothClose\r\nPosts from this author will be… [+5329 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Apple, Google add support for Thread 1.4',
   'description': 'Apple and Google are updating their smart home streaming devices to Thread 1.4. As first spotted by Matter Alpha and 9to5 Google, the latest spec has arrived on compatible Apple TVs in the tvOS 27 developer beta and the Google TV Streamer through a software u…',
   'url': 'https://www.theverge.com/tech/947888/apple-google-add-support-for-thread-1-4',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_7137.jpg?quality=90&strip=all&crop=0%2C30.191972076789%2C100%2C69.808027923211&w=1200',
   'publishedAt': '2026-06-10T20:30:33Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nIts almost time for one big Thread network!\r\nIts almost time for one big Thread network!\r\nby\r\nJennifer Pattison TuohyClose\r\nSenior Reviewer, Smart Home\r\nPosts fr… [+3614 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Janko Roettgers',
   'title': 'Is Apple TV the new HBO?',
   'description': 'This is Lowpass by Janko Roettgers, a newsletter on the ever-evolving intersection of tech and entertainment, syndicated just for The Verge subscribers once a week. Severance. Pachinko. Silo. Ted Lasso. Over the past couple of years, a number of Apple TV show…',
   'url': 'https://www.theverge.com/column/948295/apple-tv-new-hbo',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/03/Severance_Photo_020912.jpg?quality=90&strip=all&crop=0%2C10.726247800535%2C100%2C78.54750439893&w=1200',
   'publishedAt': '2026-06-11T12:19:25Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles over large catalogs.\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles o… [+6523 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Antonio G. Di Benedetto',
   'title': 'Apple announces macOS 27 Golden Gate',
   'description': "Apple has announced macOS 27 Golden Gate, the next version of its desktop operating system. The new OS for MacBooks and Mac desktops is the follow-up to last year's macOS Tahoe 26. Tahoe added some handy features, like a revised Spotlight search and a Phone a…",
   'url': 'https://www.theverge.com/tech/943695/apple-wwdc-2026-macos-27-macbook-mac-announcement-features',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK071_APPLE_D.webp?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T17:07:30Z',
   'content': "Apple has announced macOS 27 Golden Gate, the next version of its desktop operating system.\nThe new OS for MacBooks and Mac desktops is the follow-up to last year's macOS Tahoe 26. Tahoe added some h… [+439 chars]"},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Stevie Bonifield',
   'title': 'Apple announces visionOS 27 with Siri AI',
   'description': "Along with new software for Macs and iPhones, Apple announced visionOS 27 during its keynote presentation at WWDC on Monday. Like its other platforms, visionOS 27 will feature Apple's updated Siri AI assistant and the new dedicated Siri app. You can use visua…",
   'url': 'https://www.theverge.com/tech/944129/apple-visionos-updates-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/wwdc2026-visionos27.png?quality=90&strip=all&crop=0%2C9.6904971505351%2C100%2C80.61900569893&w=1200',
   'publishedAt': '2026-06-08T18:32:00Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe latest version of Apples mixed reality OS debuts at WWDC.\r\nThe latest version of Apples mixed reality OS debuts at WWDC.\r\nby\r\nStevie BonifieldClose\r\nPosts fr… [+2266 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jess Weatherbed',
   'title': 'Apple announces watchOS 27, now with Siri AI',
   'description': 'Apple just announced watchOS 27, the next version of its Apple Watch operating system, introducing support for Siri AI, a redesigned "dynamic" app grid, and improvements to health and fitness tracking. The watchOS 27 update will be available "this fall," acco…',
   'url': 'https://www.theverge.com/tech/943145/apple-watch-watchos-27-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Apple-Watch-watchOS-27-Siri-AI.jpg?quality=90&strip=all&crop=0,14.033409967608,100,71.933180064785',
   'publishedAt': '2026-06-08T19:34:10Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe upcoming update will be limited to Apples more recent Watch models.\r\nThe upcoming update will be limited to Apples more recent Watch models.\r\nby\r\nJess Weathe… [+4841 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Sheena Vasani',
   'title': 'The Apple Watch Series 11 is back to its best price',
   'description': 'Apple’s upcoming watchOS 27 update will bring Siri AI and other exciting features to the Apple Watch Series 9 and newer Apple Watch models. If you’re contemplating an upgrade, all colorways of the GPS-enabled 42mm Apple Watch Series 11 — the latest model — ar…',
   'url': 'https://www.theverge.com/gadgets/947773/apple-watch-series-11-beats-studio-buds-plus-deal-sale',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/12/Apple-Watch-Series-11-deal.png?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-10T14:57:20Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe slick Beats Studio Buds Plus are also on sale for just $100, and Fujifilms fun Instax Mini 12 is even cheaper.\r\nThe slick Beats Studio Buds Plus are also on … [+4447 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Victoria Song, Nilay Patel',
   'title': 'WWDC 2026 bonus live blog: Tech Talk with Craig Federighi',
   'description': 'Fresh off the WWDC keynote presentation, The Verge has been invited to an "on-the-record technical deep dive into the bold new architecture enabling Apple Intelligence capabilities." Apple SVP of Software Engineering Craig Federighi and his team will be there…',
   'url': 'https://www.theverge.com/tech/946046/wwdc-2026-live-blog-tech-talk-with-craig-federighi',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/wwdc-2026-the-verge-55_32.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T18:46:33Z',
   'content': 'One of the funnier parts of the keynote.\r\n\n\nFresh off the WWDC keynote presentation, The Verge has been invited to an "on-the-record technical deep dive into the bold new architecture enabling Apple … [+915 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jay Peters',
   'title': 'WWDC protesters want Apple to ban Elon Musk’s apps',
   'description': 'Apple\'s big developer conference is today, and protesters are using the occasion to call on the company to remove "nudify apps" from the App Store and pull "known" child sexual abuse material from iCloud. Outside the visitor\'s center at Apple\'s Cupertino camp…',
   'url': 'https://www.theverge.com/tech/945813/apple-wwdc-protesters-deepfake-nude-apps-ultraviolet-heat-initiative',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_1699.jpg?quality=90&strip=all&crop=0%2C15.095986038394%2C100%2C69.808027923211&w=1200',
   'publishedAt': '2026-06-08T16:37:09Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nTheyre also demanding a crackdown on child abuse imagery in iCloud.\r\nTheyre also demanding a crackdown on child abuse imagery in iCloud.\r\nby\r\nJay PetersClose\r\nPo… [+2186 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Stevie Bonifield',
   'title': 'The App Store is going to add subscription bundles soon',
   'description': "Later this year, you will be able to get bundled subscriptions for iPhone apps, as Apple announced it's expanding App Store bundles so they can include offers from different companies. It's similar to streaming video bundles that have combined offers for Appl…",
   'url': 'https://www.theverge.com/tech/947365/apple-subscription-bundles-app-store',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23925966/acastro_STK045_01.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-09T21:30:48Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nby\r\nStevie Bonifiel… [+2188 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Allison Johnson',
   'title': 'Here comes new Siri again',

In [29]:
data = response.json()
type(data)
data

{'status': 'ok',
 'totalResults': 37427,
 'articles': [{'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Louryn Strampe',
   'title': 'Memorial Day Tech Deals: Sony, Apple, Beats (2026)',
   'description': 'Lots of our most-recommended headphones, power banks, and other gadgets are on sale for Memorial Day.',
   'url': 'https://www.wired.com/story/memorial-day-tech-deals-2026-1/',
   'urlToImage': 'https://media.wired.com/photos/6a06188db84b146a9eec38c1/191:100/w_1280,c_limit/Memorial%20Day%20Deals%20Tech%20top%20art%20052026%20SOURCE%20Amazon.jpg',
   'publishedAt': '2026-05-22T18:52:47Z',
   'content': "When you think of Memorial Day sales, you probably think of mattresses and other home goods. And while those items are definitely discounted, now is also a good time to purchase tech. Personally, I'm… [+1064 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Luke Larsen',
   'title': 'MacOS 27 Golden Gate: Top New Features',
   'description': "Apple has announced the latest version of macOS. It's all about the reintroduction of Siri, which is now accessible from anywhere on the Mac desktop.",
   'url': 'https://www.wired.com/story/macos-27-golden-gate-top-features/',
   'urlToImage': 'https://media.wired.com/photos/6a2849c20d6aa02c6a8cdf9e/191:100/w_1280,c_limit/Apple-OS-27-updates-260608.jpg',
   'publishedAt': '2026-06-09T17:33:21Z',
   'content': 'One of the most interesting new features is Custom Extensions, which lets you create an extension for Safari in natural language. Lastly, the new version of Safari will work the Passwords app to auto… [+2328 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Julian Chokkattu',
   'title': 'Apple’s iPhone Camera App Is Getting an AI Upgrade in iOS 27',
   'description': 'Siri is now directly embedded into the camera app, and there are more artificial intelligence tools in the Photos app to alter your images.',
   'url': 'https://www.wired.com/story/apples-iphone-camera-app-is-getting-an-ai-upgrade-in-ios-27/',
   'urlToImage': 'https://media.wired.com/photos/6a270a0e623237895b48f975/191:100/w_1280,c_limit/apple-camera-app-gear-2233007119.jpg',
   'publishedAt': '2026-06-08T18:40:32Z',
   'content': 'Your iPhone camera app will look a little different this fall. On Monday at its annual Worldwide Developers Conference in Cupertino, California, Apple showed off new features in its next version of i… [+2335 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Boutayna Chokrane',
   'title': '2 Best Bluetooth Trackers of 2026, Plus Honorable Mentions',
   'description': 'Constantly losing your stuff? Here are the best Bluetooth trackers to help you keep everything in check—plus some guidance on staying safe while using them.',
   'url': 'https://www.wired.com/story/the-best-bluetooth-trackers/',
   'urlToImage': 'https://media.wired.com/photos/6a232b2b713a46b95a632884/191:100/w_1280,c_limit/The-Best-Bluetooth-Trackers.jpg',
   'publishedAt': '2026-06-06T10:38:00Z',
   'content': "I'd like to believe I'm organized. Reality suggests otherwise. I've left my smartphone in the refrigerator and spent hours searching for it. I've misplaced my AirPods and Oura Ring for days at a time… [+2518 chars]"},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Luke Larsen',
   'title': 'I Never Liked a Laptop Sleeve Until I Tried the Bellroy Laptop Caddy',
   'description': "The Bellroy Laptop Caddy is actually so much more than a laptop sleeve. With all the extra space and pockets, it's the best laptop companion I've ever used.",
   'url': 'https://www.wired.com/story/finally-a-laptop-sleeve-for-me/',
   'urlToImage': 'https://media.wired.com/photos/6a0cabd72c7ee96598e09971/191:100/w_1280,c_limit/Bellroy%20Laptop%20Caddy%20SOURCE%20Bellroy%20(Bag%20Check).jpg',
   'publishedAt': '2026-05-26T09:32:00Z',
   'content': 'As we get out of the house, the gear-obsessed WIRED Reviews team is writing about our favorite bags and EDCs. Today, reviewer Luke Larsenraves about his love for his Bellroy Laptop Caddy. You can als… [+2204 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Paresh Dave, Lauren Goode, Zoë Schiffer',
   'title': 'Meta Employees Are Scrambling to Use Up Benefits Ahead of Layoffs',
   'description': 'On the eve of about 8,000 jobs being cut, employees are cashing in on headphone stipends and other perks while they still can.',
   'url': 'https://www.wired.com/story/meta-employees-scramble-benefits-layoffs-ai/',
   'urlToImage': 'https://media.wired.com/photos/6a0cb2b791b600abc11af14d/191:100/w_1280,c_limit/Meta-Employees-Scrambling-to-Use-Up-Benefits-Ahead-of-Layoffs-Business-2272777092.jpg',
   'publishedAt': '2026-05-19T19:00:46Z',
   'content': 'Ahead of Metas latest round of mass layoffs tomorrow, some employees are deserting offices, abandoning their work, and loading up on perks they might soon lose, several people at the company tell WIR… [+2885 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Cameras get an Apple Intelligence boost in Apple Home',
   'description': 'Apple Intelligence is coming to cameras connected to Apple Home. At WWDC, Apple announced that with iOS27, the Home app will use Apple Intelligence to analyze footage and generate descriptions summarizing what the camera saw. You can also search footage with …',
   'url': 'https://www.theverge.com/tech/946032/apple-home-ai-camera-descriptions-search-4k',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Screenshot-2026-06-08-at-1.58.57PM.png?quality=90&strip=all&crop=0%2C3.5746394385138%2C100%2C92.850721122972&w=1200',
   'publishedAt': '2026-06-08T18:50:04Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nSecurity cameras connected to the Home app can use AI to search footage, and HomeKit Secure Video will finally support 4K resolution.\r\nSecurity cameras connected… [+2622 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jay Peters',
   'title': 'Apple announces iOS 27',
   'description': 'Apple announced its next major iOS update, iOS 27, at WWDC 2026 on Monday. Apple is highlighting performance and design improvements as a major feature, and the update will be supported all the way back to the iPhone 11. A big change is an opacity slider for …',
   'url': 'https://www.theverge.com/tech/941202/apple-ios-27-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/STK071_APPLE_E.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T17:23:57Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nYour iPhone is getting new features.\r\nYour iPhone is getting new features.\r\nby\r\nJay PetersClose\r\nPosts from this author will be added to your daily email digest … [+2895 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Andrew Liszewski',
   'title': 'Apple announces iPadOS 27',
   'description': "Today at Apple's Worldwide Developers Conference, the company announced new features coming to the iPad with iPadOS 27 including optimizations such as apps launching up to 30 percent faster by intelligently preloading needed info, and more responsive switchin…",
   'url': 'https://www.theverge.com/tech/942546/apple-ipados-27-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/ipados1.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T17:51:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe iPads next big update is expected to arrive later this year.\r\nThe iPads next big update is expected to arrive later this year.\r\nby\r\nAndrew LiszewskiClose\r\nPo… [+3864 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Robert Hart',
   'title': 'Apple wants Europe to blink',
   'description': "It took a few years, but Apple finally made its AI look useful. Now millions of iPhone users in Europe are being told they won't be getting Siri AI anytime soon, if ever - and Apple wants them to blame the EU. Apple says its new AI-powered Siri will not launc…",
   'url': 'https://www.theverge.com/ai-artificial-intelligence/947051/apple-europe-dma-siri-ai',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK450_EU_G.jpg?quality=90&strip=all&crop=0%2C9.9676601489831%2C100%2C80.064679702034&w=1200',
   'publishedAt': '2026-06-09T17:13:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nApple wants Europe to blink\r\nApple blames DMA for delaying Siri AI in Europe. The EU says nothing is stopping Apple from launching it. \r\nby\r\nRobert HartClose\r\nPo… [+7489 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple is using AI to fix Safari’s extension problem',
   'description': "Apple is trying to solve one of Safari's biggest weaknesses with AI. Safari has long lacked the robust library of extensions that its rivals have, mainly due to the stringent development requirements from Apple. But now, Apple is inviting users to essentially…",
   'url': 'https://www.theverge.com/tech/946345/apple-safari-ai-update-extensions',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/describe-extension-safari.jpg?quality=90&strip=all&crop=0%2C10.742998834307%2C100%2C78.514002331385&w=1200',
   'publishedAt': '2026-06-08T22:14:17Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nSafari will invite users to vibe-code their own extensions.\r\nSafari will invite users to vibe-code their own extensions.\r\nby\r\nEmma RothClose\r\nPosts from this aut… [+4329 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple WWDC 2026: The 7 biggest announcements',
   'description': "Apple's keynote at this year's Worldwide Developers Conference was a big one. After months of delays, Apple reintroduced us to its AI-upgraded Siri, which will go beyond what the existing voice assistant can do by offering more personalized help. We also got …",
   'url': 'https://www.theverge.com/tech/945693/apple-wwdc-2026-biggest-announcements-ios-27',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Screenshot-2026-06-08-at-1.01.41PM.png?quality=90&strip=all&crop=0%2C2.7453349442878%2C100%2C94.509330111424&w=1200',
   'publishedAt': '2026-06-08T18:51:19Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe update-filled keynote showed an AI-upgraded Siri along with new features across Apples operating systems.\r\nby\r\nEmma RothClose\r\nPosts from this author will be… [+5329 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Apple, Google add support for Thread 1.4',
   'description': 'Apple and Google are updating their smart home streaming devices to Thread 1.4. As first spotted by Matter Alpha and 9to5 Google, the latest spec has arrived on compatible Apple TVs in the tvOS 27 developer beta and the Google TV Streamer through a software u…',
   'url': 'https://www.theverge.com/tech/947888/apple-google-add-support-for-thread-1-4',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_7137.jpg?quality=90&strip=all&crop=0%2C30.191972076789%2C100%2C69.808027923211&w=1200',
   'publishedAt': '2026-06-10T20:30:33Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nIts almost time for one big Thread network!\r\nIts almost time for one big Thread network!\r\nby\r\nJennifer Pattison TuohyClose\r\nSenior Reviewer, Smart Home\r\nPosts fr… [+3614 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Janko Roettgers',
   'title': 'Is Apple TV the new HBO?',
   'description': 'This is Lowpass by Janko Roettgers, a newsletter on the ever-evolving intersection of tech and entertainment, syndicated just for The Verge subscribers once a week. Severance. Pachinko. Silo. Ted Lasso. Over the past couple of years, a number of Apple TV show…',
   'url': 'https://www.theverge.com/column/948295/apple-tv-new-hbo',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/03/Severance_Photo_020912.jpg?quality=90&strip=all&crop=0%2C10.726247800535%2C100%2C78.54750439893&w=1200',
   'publishedAt': '2026-06-11T12:19:25Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles over large catalogs.\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles o… [+6523 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Antonio G. Di Benedetto',
   'title': 'Apple announces macOS 27 Golden Gate',
   'description': "Apple has announced macOS 27 Golden Gate, the next version of its desktop operating system. The new OS for MacBooks and Mac desktops is the follow-up to last year's macOS Tahoe 26. Tahoe added some handy features, like a revised Spotlight search and a Phone a…",
   'url': 'https://www.theverge.com/tech/943695/apple-wwdc-2026-macos-27-macbook-mac-announcement-features',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK071_APPLE_D.webp?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T17:07:30Z',
   'content': "Apple has announced macOS 27 Golden Gate, the next version of its desktop operating system.\nThe new OS for MacBooks and Mac desktops is the follow-up to last year's macOS Tahoe 26. Tahoe added some h… [+439 chars]"},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Stevie Bonifield',
   'title': 'Apple announces visionOS 27 with Siri AI',
   'description': "Along with new software for Macs and iPhones, Apple announced visionOS 27 during its keynote presentation at WWDC on Monday. Like its other platforms, visionOS 27 will feature Apple's updated Siri AI assistant and the new dedicated Siri app. You can use visua…",
   'url': 'https://www.theverge.com/tech/944129/apple-visionos-updates-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/wwdc2026-visionos27.png?quality=90&strip=all&crop=0%2C9.6904971505351%2C100%2C80.61900569893&w=1200',
   'publishedAt': '2026-06-08T18:32:00Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe latest version of Apples mixed reality OS debuts at WWDC.\r\nThe latest version of Apples mixed reality OS debuts at WWDC.\r\nby\r\nStevie BonifieldClose\r\nPosts fr… [+2266 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jess Weatherbed',
   'title': 'Apple announces watchOS 27, now with Siri AI',
   'description': 'Apple just announced watchOS 27, the next version of its Apple Watch operating system, introducing support for Siri AI, a redesigned "dynamic" app grid, and improvements to health and fitness tracking. The watchOS 27 update will be available "this fall," acco…',
   'url': 'https://www.theverge.com/tech/943145/apple-watch-watchos-27-wwdc-2026',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Apple-Watch-watchOS-27-Siri-AI.jpg?quality=90&strip=all&crop=0,14.033409967608,100,71.933180064785',
   'publishedAt': '2026-06-08T19:34:10Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe upcoming update will be limited to Apples more recent Watch models.\r\nThe upcoming update will be limited to Apples more recent Watch models.\r\nby\r\nJess Weathe… [+4841 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Sheena Vasani',
   'title': 'The Apple Watch Series 11 is back to its best price',
   'description': 'Apple’s upcoming watchOS 27 update will bring Siri AI and other exciting features to the Apple Watch Series 9 and newer Apple Watch models. If you’re contemplating an upgrade, all colorways of the GPS-enabled 42mm Apple Watch Series 11 — the latest model — ar…',
   'url': 'https://www.theverge.com/gadgets/947773/apple-watch-series-11-beats-studio-buds-plus-deal-sale',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/12/Apple-Watch-Series-11-deal.png?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-10T14:57:20Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe slick Beats Studio Buds Plus are also on sale for just $100, and Fujifilms fun Instax Mini 12 is even cheaper.\r\nThe slick Beats Studio Buds Plus are also on … [+4447 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Victoria Song, Nilay Patel',
   'title': 'WWDC 2026 bonus live blog: Tech Talk with Craig Federighi',
   'description': 'Fresh off the WWDC keynote presentation, The Verge has been invited to an "on-the-record technical deep dive into the bold new architecture enabling Apple Intelligence capabilities." Apple SVP of Software Engineering Craig Federighi and his team will be there…',
   'url': 'https://www.theverge.com/tech/946046/wwdc-2026-live-blog-tech-talk-with-craig-federighi',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/wwdc-2026-the-verge-55_32.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-08T18:46:33Z',
   'content': 'One of the funnier parts of the keynote.\r\n\n\nFresh off the WWDC keynote presentation, The Verge has been invited to an "on-the-record technical deep dive into the bold new architecture enabling Apple … [+915 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jay Peters',
   'title': 'WWDC protesters want Apple to ban Elon Musk’s apps',
   'description': 'Apple\'s big developer conference is today, and protesters are using the occasion to call on the company to remove "nudify apps" from the App Store and pull "known" child sexual abuse material from iCloud. Outside the visitor\'s center at Apple\'s Cupertino camp…',
   'url': 'https://www.theverge.com/tech/945813/apple-wwdc-protesters-deepfake-nude-apps-ultraviolet-heat-initiative',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_1699.jpg?quality=90&strip=all&crop=0%2C15.095986038394%2C100%2C69.808027923211&w=1200',
   'publishedAt': '2026-06-08T16:37:09Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nTheyre also demanding a crackdown on child abuse imagery in iCloud.\r\nTheyre also demanding a crackdown on child abuse imagery in iCloud.\r\nby\r\nJay PetersClose\r\nPo… [+2186 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Stevie Bonifield',
   'title': 'The App Store is going to add subscription bundles soon',
   'description': "Later this year, you will be able to get bundled subscriptions for iPhone apps, as Apple announced it's expanding App Store bundles so they can include offers from different companies. It's similar to streaming video bundles that have combined offers for Appl…",
   'url': 'https://www.theverge.com/tech/947365/apple-subscription-bundles-app-store',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23925966/acastro_STK045_01.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-06-09T21:30:48Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nby\r\nStevie Bonifiel… [+2188 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Allison Johnson',
   'title': 'Here comes new Siri again',

In [30]:
articles = data['articles']
type(articles)
articles

[{'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Louryn Strampe',
  'title': 'Memorial Day Tech Deals: Sony, Apple, Beats (2026)',
  'description': 'Lots of our most-recommended headphones, power banks, and other gadgets are on sale for Memorial Day.',
  'url': 'https://www.wired.com/story/memorial-day-tech-deals-2026-1/',
  'urlToImage': 'https://media.wired.com/photos/6a06188db84b146a9eec38c1/191:100/w_1280,c_limit/Memorial%20Day%20Deals%20Tech%20top%20art%20052026%20SOURCE%20Amazon.jpg',
  'publishedAt': '2026-05-22T18:52:47Z',
  'content': "When you think of Memorial Day sales, you probably think of mattresses and other home goods. And while those items are definitely discounted, now is also a good time to purchase tech. Personally, I'm… [+1064 chars]"},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Luke Larsen',
  'title': 'MacOS 27 Golden Gate: Top New Features',
  'description': "Apple has announced the latest version of macOS. It's all about the reintroduction of Siri, which is now accessible from anywhere on the Mac desktop.",
  'url': 'https://www.wired.com/story/macos-27-golden-gate-top-features/',
  'urlToImage': 'https://media.wired.com/photos/6a2849c20d6aa02c6a8cdf9e/191:100/w_1280,c_limit/Apple-OS-27-updates-260608.jpg',
  'publishedAt': '2026-06-09T17:33:21Z',
  'content': 'One of the most interesting new features is Custom Extensions, which lets you create an extension for Safari in natural language. Lastly, the new version of Safari will work the Passwords app to auto… [+2328 chars]'},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Julian Chokkattu',
  'title': 'Apple’s iPhone Camera App Is Getting an AI Upgrade in iOS 27',
  'description': 'Siri is now directly embedded into the camera app, and there are more artificial intelligence tools in the Photos app to alter your images.',
  'url': 'https://www.wired.com/story/apples-iphone-camera-app-is-getting-an-ai-upgrade-in-ios-27/',
  'urlToImage': 'https://media.wired.com/photos/6a270a0e623237895b48f975/191:100/w_1280,c_limit/apple-camera-app-gear-2233007119.jpg',
  'publishedAt': '2026-06-08T18:40:32Z',
  'content': 'Your iPhone camera app will look a little different this fall. On Monday at its annual Worldwide Developers Conference in Cupertino, California, Apple showed off new features in its next version of i… [+2335 chars]'},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Boutayna Chokrane',
  'title': '2 Best Bluetooth Trackers of 2026, Plus Honorable Mentions',
  'description': 'Constantly losing your stuff? Here are the best Bluetooth trackers to help you keep everything in check—plus some guidance on staying safe while using them.',
  'url': 'https://www.wired.com/story/the-best-bluetooth-trackers/',
  'urlToImage': 'https://media.wired.com/photos/6a232b2b713a46b95a632884/191:100/w_1280,c_limit/The-Best-Bluetooth-Trackers.jpg',
  'publishedAt': '2026-06-06T10:38:00Z',
  'content': "I'd like to believe I'm organized. Reality suggests otherwise. I've left my smartphone in the refrigerator and spent hours searching for it. I've misplaced my AirPods and Oura Ring for days at a time… [+2518 chars]"},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Luke Larsen',
  'title': 'I Never Liked a Laptop Sleeve Until I Tried the Bellroy Laptop Caddy',
  'description': "The Bellroy Laptop Caddy is actually so much more than a laptop sleeve. With all the extra space and pockets, it's the best laptop companion I've ever used.",
  'url': 'https://www.wired.com/story/finally-a-laptop-sleeve-for-me/',
  'urlToImage': 'https://media.wired.com/photos/6a0cabd72c7ee96598e09971/191:100/w_1280,c_limit/Bellroy%20Laptop%20Caddy%20SOURCE%20Bellroy%20(Bag%20Check).jpg',
  'publishedAt': '2026-05-26T09:32:00Z',
  'content': 'As we get out of the house, the gear-obsessed WIRED Reviews team is writing about our favorite bags and EDCs. Today, reviewer Luke Larsenraves about his love for his Bellroy Laptop Caddy. You can als… [+2204 chars]'},
 {'source': {'id': 'wired', 'name': 'Wired'},
  'author': 'Paresh Dave, Lauren Goode, Zoë Schiffer',
  'title': 'Meta Employees Are Scrambling to Use Up Benefits Ahead of Layoffs',
  'description': 'On the eve of about 8,000 jobs being cut, employees are cashing in on headphone stipends and other perks while they still can.',
  'url': 'https://www.wired.com/story/meta-employees-scramble-benefits-layoffs-ai/',
  'urlToImage': 'https://media.wired.com/photos/6a0cb2b791b600abc11af14d/191:100/w_1280,c_limit/Meta-Employees-Scrambling-to-Use-Up-Benefits-Ahead-of-Layoffs-Business-2272777092.jpg',
  'publishedAt': '2026-05-19T19:00:46Z',
  'content': 'Ahead of Metas latest round of mass layoffs tomorrow, some employees are deserting offices, abandoning their work, and loading up on perks they might soon lose, several people at the company tell WIR… [+2885 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jennifer Pattison Tuohy',
  'title': 'Cameras get an Apple Intelligence boost in Apple Home',
  'description': 'Apple Intelligence is coming to cameras connected to Apple Home. At WWDC, Apple announced that with iOS27, the Home app will use Apple Intelligence to analyze footage and generate descriptions summarizing what the camera saw. You can also search footage with …',
  'url': 'https://www.theverge.com/tech/946032/apple-home-ai-camera-descriptions-search-4k',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Screenshot-2026-06-08-at-1.58.57PM.png?quality=90&strip=all&crop=0%2C3.5746394385138%2C100%2C92.850721122972&w=1200',
  'publishedAt': '2026-06-08T18:50:04Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nSecurity cameras connected to the Home app can use AI to search footage, and HomeKit Secure Video will finally support 4K resolution.\r\nSecurity cameras connected… [+2622 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jay Peters',
  'title': 'Apple announces iOS 27',
  'description': 'Apple announced its next major iOS update, iOS 27, at WWDC 2026 on Monday. Apple is highlighting performance and design improvements as a major feature, and the update will be supported all the way back to the iPhone 11. A big change is an opacity slider for …',
  'url': 'https://www.theverge.com/tech/941202/apple-ios-27-wwdc-2026',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/STK071_APPLE_E.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-08T17:23:57Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nYour iPhone is getting new features.\r\nYour iPhone is getting new features.\r\nby\r\nJay PetersClose\r\nPosts from this author will be added to your daily email digest … [+2895 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Andrew Liszewski',
  'title': 'Apple announces iPadOS 27',
  'description': "Today at Apple's Worldwide Developers Conference, the company announced new features coming to the iPad with iPadOS 27 including optimizations such as apps launching up to 30 percent faster by intelligently preloading needed info, and more responsive switchin…",
  'url': 'https://www.theverge.com/tech/942546/apple-ipados-27-wwdc-2026',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/ipados1.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-08T17:51:14Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe iPads next big update is expected to arrive later this year.\r\nThe iPads next big update is expected to arrive later this year.\r\nby\r\nAndrew LiszewskiClose\r\nPo… [+3864 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Robert Hart',
  'title': 'Apple wants Europe to blink',
  'description': "It took a few years, but Apple finally made its AI look useful. Now millions of iPhone users in Europe are being told they won't be getting Siri AI anytime soon, if ever - and Apple wants them to blame the EU. Apple says its new AI-powered Siri will not launc…",
  'url': 'https://www.theverge.com/ai-artificial-intelligence/947051/apple-europe-dma-siri-ai',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK450_EU_G.jpg?quality=90&strip=all&crop=0%2C9.9676601489831%2C100%2C80.064679702034&w=1200',
  'publishedAt': '2026-06-09T17:13:14Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nApple wants Europe to blink\r\nApple blames DMA for delaying Siri AI in Europe. The EU says nothing is stopping Apple from launching it. \r\nby\r\nRobert HartClose\r\nPo… [+7489 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Emma Roth',
  'title': 'Apple is using AI to fix Safari’s extension problem',
  'description': "Apple is trying to solve one of Safari's biggest weaknesses with AI. Safari has long lacked the robust library of extensions that its rivals have, mainly due to the stringent development requirements from Apple. But now, Apple is inviting users to essentially…",
  'url': 'https://www.theverge.com/tech/946345/apple-safari-ai-update-extensions',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/describe-extension-safari.jpg?quality=90&strip=all&crop=0%2C10.742998834307%2C100%2C78.514002331385&w=1200',
  'publishedAt': '2026-06-08T22:14:17Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nSafari will invite users to vibe-code their own extensions.\r\nSafari will invite users to vibe-code their own extensions.\r\nby\r\nEmma RothClose\r\nPosts from this aut… [+4329 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Emma Roth',
  'title': 'Apple WWDC 2026: The 7 biggest announcements',
  'description': "Apple's keynote at this year's Worldwide Developers Conference was a big one. After months of delays, Apple reintroduced us to its AI-upgraded Siri, which will go beyond what the existing voice assistant can do by offering more personalized help. We also got …",
  'url': 'https://www.theverge.com/tech/945693/apple-wwdc-2026-biggest-announcements-ios-27',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Screenshot-2026-06-08-at-1.01.41PM.png?quality=90&strip=all&crop=0%2C2.7453349442878%2C100%2C94.509330111424&w=1200',
  'publishedAt': '2026-06-08T18:51:19Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe update-filled keynote showed an AI-upgraded Siri along with new features across Apples operating systems.\r\nby\r\nEmma RothClose\r\nPosts from this author will be… [+5329 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jennifer Pattison Tuohy',
  'title': 'Apple, Google add support for Thread 1.4',
  'description': 'Apple and Google are updating their smart home streaming devices to Thread 1.4. As first spotted by Matter Alpha and 9to5 Google, the latest spec has arrived on compatible Apple TVs in the tvOS 27 developer beta and the Google TV Streamer through a software u…',
  'url': 'https://www.theverge.com/tech/947888/apple-google-add-support-for-thread-1-4',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_7137.jpg?quality=90&strip=all&crop=0%2C30.191972076789%2C100%2C69.808027923211&w=1200',
  'publishedAt': '2026-06-10T20:30:33Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nIts almost time for one big Thread network!\r\nIts almost time for one big Thread network!\r\nby\r\nJennifer Pattison TuohyClose\r\nSenior Reviewer, Smart Home\r\nPosts fr… [+3614 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Janko Roettgers',
  'title': 'Is Apple TV the new HBO?',
  'description': 'This is Lowpass by Janko Roettgers, a newsletter on the ever-evolving intersection of tech and entertainment, syndicated just for The Verge subscribers once a week. Severance. Pachinko. Silo. Ted Lasso. Over the past couple of years, a number of Apple TV show…',
  'url': 'https://www.theverge.com/column/948295/apple-tv-new-hbo',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/03/Severance_Photo_020912.jpg?quality=90&strip=all&crop=0%2C10.726247800535%2C100%2C78.54750439893&w=1200',
  'publishedAt': '2026-06-11T12:19:25Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles over large catalogs.\r\nUnlike competitors like Netflix, Apple TV emphasizes tentpole titles o… [+6523 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Antonio G. Di Benedetto',
  'title': 'Apple announces macOS 27 Golden Gate',
  'description': "Apple has announced macOS 27 Golden Gate, the next version of its desktop operating system. The new OS for MacBooks and Mac desktops is the follow-up to last year's macOS Tahoe 26. Tahoe added some handy features, like a revised Spotlight search and a Phone a…",
  'url': 'https://www.theverge.com/tech/943695/apple-wwdc-2026-macos-27-macbook-mac-announcement-features',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/STK071_APPLE_D.webp?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-08T17:07:30Z',
  'content': "Apple has announced macOS 27 Golden Gate, the next version of its desktop operating system.\nThe new OS for MacBooks and Mac desktops is the follow-up to last year's macOS Tahoe 26. Tahoe added some h… [+439 chars]"},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Stevie Bonifield',
  'title': 'Apple announces visionOS 27 with Siri AI',
  'description': "Along with new software for Macs and iPhones, Apple announced visionOS 27 during its keynote presentation at WWDC on Monday. Like its other platforms, visionOS 27 will feature Apple's updated Siri AI assistant and the new dedicated Siri app. You can use visua…",
  'url': 'https://www.theverge.com/tech/944129/apple-visionos-updates-wwdc-2026',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/wwdc2026-visionos27.png?quality=90&strip=all&crop=0%2C9.6904971505351%2C100%2C80.61900569893&w=1200',
  'publishedAt': '2026-06-08T18:32:00Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe latest version of Apples mixed reality OS debuts at WWDC.\r\nThe latest version of Apples mixed reality OS debuts at WWDC.\r\nby\r\nStevie BonifieldClose\r\nPosts fr… [+2266 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jess Weatherbed',
  'title': 'Apple announces watchOS 27, now with Siri AI',
  'description': 'Apple just announced watchOS 27, the next version of its Apple Watch operating system, introducing support for Siri AI, a redesigned "dynamic" app grid, and improvements to health and fitness tracking. The watchOS 27 update will be available "this fall," acco…',
  'url': 'https://www.theverge.com/tech/943145/apple-watch-watchos-27-wwdc-2026',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/Apple-Watch-watchOS-27-Siri-AI.jpg?quality=90&strip=all&crop=0,14.033409967608,100,71.933180064785',
  'publishedAt': '2026-06-08T19:34:10Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe upcoming update will be limited to Apples more recent Watch models.\r\nThe upcoming update will be limited to Apples more recent Watch models.\r\nby\r\nJess Weathe… [+4841 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Sheena Vasani',
  'title': 'The Apple Watch Series 11 is back to its best price',
  'description': 'Apple’s upcoming watchOS 27 update will bring Siri AI and other exciting features to the Apple Watch Series 9 and newer Apple Watch models. If you’re contemplating an upgrade, all colorways of the GPS-enabled 42mm Apple Watch Series 11 — the latest model — ar…',
  'url': 'https://www.theverge.com/gadgets/947773/apple-watch-series-11-beats-studio-buds-plus-deal-sale',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/12/Apple-Watch-Series-11-deal.png?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-10T14:57:20Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nThe slick Beats Studio Buds Plus are also on sale for just $100, and Fujifilms fun Instax Mini 12 is even cheaper.\r\nThe slick Beats Studio Buds Plus are also on … [+4447 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Victoria Song, Nilay Patel',
  'title': 'WWDC 2026 bonus live blog: Tech Talk with Craig Federighi',
  'description': 'Fresh off the WWDC keynote presentation, The Verge has been invited to an "on-the-record technical deep dive into the bold new architecture enabling Apple Intelligence capabilities." Apple SVP of Software Engineering Craig Federighi and his team will be there…',
  'url': 'https://www.theverge.com/tech/946046/wwdc-2026-live-blog-tech-talk-with-craig-federighi',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/wwdc-2026-the-verge-55_32.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-08T18:46:33Z',
  'content': 'One of the funnier parts of the keynote.\r\n\n\nFresh off the WWDC keynote presentation, The Verge has been invited to an "on-the-record technical deep dive into the bold new architecture enabling Apple … [+915 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Jay Peters',
  'title': 'WWDC protesters want Apple to ban Elon Musk’s apps',
  'description': 'Apple\'s big developer conference is today, and protesters are using the occasion to call on the company to remove "nudify apps" from the App Store and pull "known" child sexual abuse material from iCloud. Outside the visitor\'s center at Apple\'s Cupertino camp…',
  'url': 'https://www.theverge.com/tech/945813/apple-wwdc-protesters-deepfake-nude-apps-ultraviolet-heat-initiative',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/06/IMG_1699.jpg?quality=90&strip=all&crop=0%2C15.095986038394%2C100%2C69.808027923211&w=1200',
  'publishedAt': '2026-06-08T16:37:09Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nTheyre also demanding a crackdown on child abuse imagery in iCloud.\r\nTheyre also demanding a crackdown on child abuse imagery in iCloud.\r\nby\r\nJay PetersClose\r\nPo… [+2186 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Stevie Bonifield',
  'title': 'The App Store is going to add subscription bundles soon',
  'description': "Later this year, you will be able to get bundled subscriptions for iPhone apps, as Apple announced it's expanding App Store bundles so they can include offers from different companies. It's similar to streaming video bundles that have combined offers for Appl…",
  'url': 'https://www.theverge.com/tech/947365/apple-subscription-bundles-app-store',
  'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/23925966/acastro_STK045_01.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
  'publishedAt': '2026-06-09T21:30:48Z',
  'content': '<ul><li></li><li></li><li></li></ul>\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nAlong with iOS 27, Apple also announced big changes to the App Store.\r\nby\r\nStevie Bonifiel… [+2188 chars]'},
 {'source': {'id': 'the-verge', 'name': 'The Verge'},
  'author': 'Allison Johnson',
  'title': 'Here comes new Siri again',

In [31]:
articles_df = pd.DataFrame(articles)
articles_df.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'wired', 'name': 'Wired'}",Louryn Strampe,"Memorial Day Tech Deals: Sony, Apple, Beats (2...","Lots of our most-recommended headphones, power...",https://www.wired.com/story/memorial-day-tech-...,https://media.wired.com/photos/6a06188db84b146...,2026-05-22T18:52:47Z,"When you think of Memorial Day sales, you prob..."
1,"{'id': 'wired', 'name': 'Wired'}",Luke Larsen,MacOS 27 Golden Gate: Top New Features,Apple has announced the latest version of macO...,https://www.wired.com/story/macos-27-golden-ga...,https://media.wired.com/photos/6a2849c20d6aa02...,2026-06-09T17:33:21Z,One of the most interesting new features is Cu...
2,"{'id': 'wired', 'name': 'Wired'}",Julian Chokkattu,Apple’s iPhone Camera App Is Getting an AI Upg...,Siri is now directly embedded into the camera ...,https://www.wired.com/story/apples-iphone-came...,https://media.wired.com/photos/6a270a0e6232378...,2026-06-08T18:40:32Z,Your iPhone camera app will look a little diff...
3,"{'id': 'wired', 'name': 'Wired'}",Boutayna Chokrane,"2 Best Bluetooth Trackers of 2026, Plus Honora...",Constantly losing your stuff? Here are the bes...,https://www.wired.com/story/the-best-bluetooth...,https://media.wired.com/photos/6a232b2b713a46b...,2026-06-06T10:38:00Z,I'd like to believe I'm organized. Reality sug...
4,"{'id': 'wired', 'name': 'Wired'}",Luke Larsen,I Never Liked a Laptop Sleeve Until I Tried th...,The Bellroy Laptop Caddy is actually so much m...,https://www.wired.com/story/finally-a-laptop-s...,https://media.wired.com/photos/6a0cabd72c7ee96...,2026-05-26T09:32:00Z,"As we get out of the house, the gear-obsessed ..."

In [32]:
# drop column source

articles_df = articles_df.drop(columns={'source', 'urlToImage'})
articles_df.head()

,author,title,description,url,publishedAt,content
0,Louryn Strampe,"Memorial Day Tech Deals: Sony, Apple, Beats (2...","Lots of our most-recommended headphones, power...",https://www.wired.com/story/memorial-day-tech-...,2026-05-22T18:52:47Z,"When you think of Memorial Day sales, you prob..."
1,Luke Larsen,MacOS 27 Golden Gate: Top New Features,Apple has announced the latest version of macO...,https://www.wired.com/story/macos-27-golden-ga...,2026-06-09T17:33:21Z,One of the most interesting new features is Cu...
2,Julian Chokkattu,Apple’s iPhone Camera App Is Getting an AI Upg...,Siri is now directly embedded into the camera ...,https://www.wired.com/story/apples-iphone-came...,2026-06-08T18:40:32Z,Your iPhone camera app will look a little diff...
3,Boutayna Chokrane,"2 Best Bluetooth Trackers of 2026, Plus Honora...",Constantly losing your stuff? Here are the bes...,https://www.wired.com/story/the-best-bluetooth...,2026-06-06T10:38:00Z,I'd like to believe I'm organized. Reality sug...
4,Luke Larsen,I Never Liked a Laptop Sleeve Until I Tried th...,The Bellroy Laptop Caddy is actually so much m...,https://www.wired.com/story/finally-a-laptop-s...,2026-05-26T09:32:00Z,"As we get out of the house, the gear-obsessed ..."

In [33]:
# store to db

DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

engine = create_engine(f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

articles_df.to_sql('articles', con=engine, if_exists='replace', index=False)

62